@echo off
chcp 65001 > nul
setlocal enabledelayedexpansion

:: =================================================================
:: INITIALIZATION & ENVIRONMENT SETUP
:: =================================================================

:: Get the current year for archiving tools
for /f "tokens=2 delims==" %%I in ('wmic os get localdatetime /value') do set datetime=%%I
set "Yeardate=%datetime:~0,4%"

:: Load configuration
set "CONFIG_FILE=%~dp0skyrim_config.ini"

:INIT_CHECK
if not exist "%CONFIG_FILE%" goto RUN_SETUP_ROUTINE
for /f "usebackq delims=" %%I in ("%CONFIG_FILE%") do set "%%I"

:: Validate required paths
if "%SKYRIM_DIR%"=="" goto RUN_SETUP_ROUTINE
if "%SKSE_PATH%"=="" goto RUN_SETUP_ROUTINE
if "%VORTEX_EXE%"=="" goto RUN_SETUP_ROUTINE
if "%VORTEX_DIR%"=="" goto RUN_SETUP_ROUTINE

:MAIN_MENU
:: =================================================================
:: MAIN MENU CRASH LOG AUTO-DETECTOR
:: =================================================================
set "NEW_LOG_FOUND=FALSE"

:: Define standard crash log locations using your config's DOCS_BASE
set "SKSE_LOG_DIR=%DOCS_BASE%\My Games\Skyrim Special Edition\SKSE"
set "NETSCRIPT_LOG_DIR=%DOCS_BASE%\My Games\Skyrim Special Edition\NetScriptFramework\Crash"

:: Check SKSE CrashLogger files modified today
if exist "%SKSE_LOG_DIR%\crash-*.log" (
    forfiles /p "%SKSE_LOG_DIR%" /m "crash-*.log" /d +0 >nul 2>&1 && set "NEW_LOG_FOUND=TRUE"
)

:: Check NetScriptFramework files modified today
if exist "%NETSCRIPT_LOG_DIR%\crash-*.txt" (
    forfiles /p "%NETSCRIPT_LOG_DIR%" /m "crash-*.txt" /d +0 >nul 2>&1 && set "NEW_LOG_FOUND=TRUE"
)

cls
echo =================================================================
echo                SKYRIM SE/AE CONTROL CENTER ENGINE v1.0
echo =================================================================
echo   [Skyrim Dir]   %SKYRIM_DIR%
echo   [Mod Staging]  %VORTEX_DIR%
echo   [Documents]    %DOCS_BASE%
echo =================================================================

if "!NEW_LOG_FOUND!"=="TRUE" (
    echo  [⚠️ NOTICE] A new crash log was detected from today!
    echo             Type 8 to analyze it directly.
    echo =================================================================
)

echo    [1] 🌐 WEB:      Open Nexus Mods Skyrim SE Hub
echo.
echo    [2] 🛠️  UTILITY:  Launch Mod Manager (Background)
echo        Note: Initialization logs from the manager may appear briefly.
echo.
echo    [3] 📂 EXPLORER: Directory Hub ^& Crash Log Analyzer
echo.
echo    [4] 🚀 LAUNCH:   Boot Game (SKSE Loader / Vanilla Game EXE)
echo.
echo    [5] 📋 INVENTORY: Scan Active Data Plugins (.esp/.esm/.esl)
echo.
echo    [6] 🩺 DIAGNOSTIC: Pro-Mod Plugin and Health Analysis
echo.
echo    [7] 🔄 RESETUP:  Wipe INI Profile and Rerun Setup Wizard
echo.
echo    [X] ❌ EXIT:     Terminate Engine Safely
echo =================================================================
echo.
set "main_choice="
set /p main_choice="Select execution routine (1-7, X): "

if "%main_choice%"=="1" goto HUB_NEXUS
if "%main_choice%"=="2" goto HUB_VORTEX
if "%main_choice%"=="3" goto SUB_MENU_EXPLORER
if "%main_choice%"=="4" goto SUB_MENU_LAUNCH
if "%main_choice%"=="5" goto SCAN_LOAD_ORDER
if "%main_choice%"=="6" goto ANALYZE_MOD_SIZE
if "%main_choice%"=="7" (del /q "%CONFIG_FILE%" 2>nul & goto RUN_SETUP_ROUTINE)
if "%main_choice%"=="8" goto :ANALYZE_LATEST_CRASH
if /i "%main_choice%"=="X" exit
goto MAIN_MENU

:: ===================================================
:: [1] HUB: OPEN NEXUS MODS (CMD STAYS OPEN)
:: ===================================================
:HUB_NEXUS
cls
echo Starting browser context thread for Nexus Mods...
start "" "https://www.nexusmods.com/skyrimspecialedition"
timeout /t 3 > nul
goto MAIN_MENU

:: ===================================================
:: [2] HUB: LAUNCH VORTEX (CMD STAYS OPEN)
:: ===================================================
:HUB_VORTEX
cls
echo Starting Mod Manager...
echo.
echo [INFO] Initializing handshake with external process...
echo [INFO] Note: Any initialization logs appearing below are 
echo        generated by the manager, not the Control Center.
echo.
:: Using the redirect to keep it cleaner, but this covers you if it still leaks
start "" "%VORTEX_EXE%" >nul 2>&1
echo Manager launched successfully. Returning to menu...
timeout /t 5 >nul
goto MAIN_MENU

:: ===================================================
:: [3] SUB-MENU: DIRECTORY HUB
:: ===================================================
:SUB_MENU_EXPLORER
cls
echo =================================================================
echo                   [3] Directory HUB ^& CRASH LOG ANALYZER
echo =================================================================
echo    [1] 📂 DIR: Open Root Skyrim Common Installation Folder (File Explorer)
echo.
echo    [2] 📦 DIR: Open Vortex Mod Staging Folder (File Explorer)
echo.
echo    [3] 📄 DIR: Open SKSE Crash Log Dump Directory (File Explorer)
echo.
echo    [4] 🔍 SCAN: Analyze Latest Crash Log (CMD)
echo.
echo    [B] ⬅️ BACK: Return to Main Menu
echo =================================================================
echo.
set "exp_choice="
set /p exp_choice="Select hub pipeline: "

if "%exp_choice%"=="1" (explorer "%SKYRIM_DIR%" & goto SUB_MENU_EXPLORER)
if "%exp_choice%"=="2" (explorer "%VORTEX_DIR%" & goto SUB_MENU_EXPLORER)
if "%exp_choice%"=="3" (explorer "%DOCS_BASE%\My Games\Skyrim Special Edition\SKSE" & goto SUB_MENU_EXPLORER)
if "%exp_choice%"=="4" goto ANALYZE_LATEST_CRASH
if /i "%exp_choice%"=="B" goto MAIN_MENU
goto SUB_MENU_EXPLORER

:: ===================================================
:: AUTOMATED SKSE CRASH LOG INTELLIGENCE SCANNER
:: ===================================================
:ANALYZE_LATEST_CRASH
cls
echo =================================================================
echo         🔍SKSE LAUNCHER LOG ^& CRASH ANALYZER - SELECT FILE
echo =================================================================
set "LOG_DIR=%DOCS_BASE%\My Games\Skyrim Special Edition\SKSE"

:: 1. List the newest 10 log/txt files with numbers
echo  Select a log file to analyze (1-10):
echo.
set "count=0"
pushd "%LOG_DIR%"
for /f "tokens=*" %%F in ('dir /b /o-d *.log *.txt 2^>nul') do (
    set /a count+=1
    set "FILE_!count!=%%F"
    echo   [!count!] %%F
    if !count! GEQ 10 goto :LIST_DONE
)
:LIST_DONE
popd

if %count%==0 (
    echo  [NOTICE] No logs found.
    pause & goto SUB_MENU_EXPLORER
)

:: 2. Get user input
echo.
set /p "choice=Enter selection [1-%count%] or [B] to back: "
if /i "%choice%"=="B" goto SUB_MENU_EXPLORER
if not defined FILE_%choice% goto ANALYZE_LATEST_CRASH

set "LATEST_LOG=!FILE_%choice%!"

:: 3. Perform the analysis on the selected file
cls
echo  Analyzing: %LATEST_LOG%
echo -----------------------------------------------------------------
echo =================== CRASH SIGNATURE ANALYSIS ===================
set "found_lines=0"
for /f "tokens=*" %%L in ('findstr /i /c:"EXCEPTION_ACCESS_VIOLATION" /c:"Module" /c:".dll" /c:".esp" /c:".esm" "%LOG_DIR%\%LATEST_LOG%" 2^>nul') do (
    echo   -^> %%L
    set /a found_lines+=1
)

echo -----------------------------------------------------------------
echo  [DIAGNOSTIC HINT]
if %found_lines% GTR 0 (
    echo  If you see "Module: [Name].dll" above, that is your primary suspect.
) else (
    echo  [!] No obvious crash markers found. Showing top 15 lines:
    echo.
    powershell -NoProfile -Command "Get-Content '%LOG_DIR%\%LATEST_LOG%' -TotalCount 15"
)
echo =================================================================
pause
goto ANALYZE_LATEST_CRASH

:: ===================================================
:: [4] SUB-MENU: GAME LAUNCH PIPELINE
:: ===================================================
:SUB_MENU_LAUNCH
cls
echo =================================================================
echo    🚀 GAME LAUNCH PIPELINE
echo =================================================================
echo.
echo    [1] 🧪 SKSE:  Launch via SKSE Loader (Recommended for modded games)
echo.
echo    [2] 🛡️ STOCK: Launch via Vanilla Game EXE (Safe for unmodded play)
echo.
echo    [B] ⬅️ BACK:  Return to Main Menu
echo =================================================================
echo.
set "launch_choice="
set /p launch_choice="Select execution system: "

if "%launch_choice%"=="1" goto LAUNCH_SKSE
if "%launch_choice%"=="2" goto LAUNCH_VANILLA
if /i "%launch_choice%"=="B" goto MAIN_MENU
goto SUB_MENU_LAUNCH

:LAUNCH_SKSE
cls
echo Initializing SKSE execution sequence...
if exist "%SKSE_PATH%" (
    start "" "%SKSE_PATH%"
    timeout /t 3 > nul
    exit
) else (
    echo [ERROR] skse64_loader.exe execution vector failed. Check paths.
    pause
)
goto SUB_MENU_LAUNCH

:LAUNCH_VANILLA
cls
echo Initializing Vanilla engine bypass launch...
if exist "%SKYRIM_DIR%\SkyrimSE.exe" (
    start "" "%SKYRIM_DIR%\SkyrimSE.exe"
    timeout /t 3 > nul
    exit
) else (
    echo [ERROR] SkyrimSE.exe target execution target missed.
    pause
)
goto SUB_MENU_LAUNCH

:: =================================================================
:: [5] PLUGINS MATRIX SCANNER (V. 1.3 - AUTO-SCALE SIZE AUDIT)
:: =================================================================
:SCAN_LOAD_ORDER
cls
echo =================================================================
echo            📋 ACTIVE PLUGINS MANIFEST ^& ARCHIVE SCANNER
echo =================================================================
echo  [TARGET PATH] %SKYRIM_DIR%\Data
echo =================================================================
echo.
set esm_count=0
set esp_count=0
set esl_count=0

echo  ┌──────────────────────────────────────────────────────────────┐
echo  │ [CORE MASTER ARCHIVES]                                       │
echo  └──────────────────────────────────────────────────────────────┘
pushd "%SKYRIM_DIR%\Data"
for /f "delims=" %%F in ('dir /b *.esm 2^{gt}nul') do (
    set /a esm_count+=1
    set "bytes=%%~zF"
    if !bytes! LSS 1048576 (
        set /a "kb=bytes / 1024"
        echo    ├── [ESM] [!kb! KB] %%F
    ) else (
        set /a "mb=bytes / 1048576"
        echo    ├── [ESM] [!mb! MB] %%F
    )
)
if !esm_count!==0 echo    └── (No master files detected in Data directory)

echo.
echo  ┌──────────────────────────────────────────────────────────────┐
echo  │ [LIGHT ES-LIGHT PLUGINS]                                     │
echo  └──────────────────────────────────────────────────────────────┘
for /f "delims=" %%F in ('dir /b *.esl 2^{gt}nul') do (
    set /a esl_count+=1
    set "bytes=%%~zF"
    if !bytes! LSS 1048576 (
        set /a "kb=bytes / 1024"
        echo    ├── [ESL] [!kb! KB] %%F
    ) else (
        set /a "mb=bytes / 1048576"
        echo    ├── [ESL] [!mb! MB] %%F
    )
)
if !esl_count!==0 echo    └── (No light patches detected)

echo.
echo  ┌──────────────────────────────────────────────────────────────┐
echo  │ [STANDARD MODIFICATION PLUGINS]                              │
echo  └──────────────────────────────────────────────────────────────┘
for /f "delims=" %%F in ('dir /b *.esp 2^{gt}nul') do (
    set /a esp_count+=1
    set "bytes=%%~zF"
    if !bytes! LSS 1048576 (
        set /a "kb=bytes / 1024"
        echo    ├── [ESP] [!kb! KB] %%F
    ) else (
        set /a "mb=bytes / 1048576"
        echo    ├── [ESP] [!mb! MB] %%F
    )
)
if !esp_count!==0 echo    └── (No standard plugins detected)
popd

echo.
echo =================================================================
echo                      LOAD ORDER STATISTICS              
echo =================================================================
echo   [+] Total Master Files (.esm):      !esm_count!
echo   [+] Total Light Plugins (.esl):     !esl_count!  (Bypasses 255 Limit)
echo   [+] Total Standard Plugins (.esp):  !esp_count!
echo -----------------------------------------------------------------
set /a total_plugins=esm_count+esp_count+esl_count
echo   [=] TOTAL ACTIVE PLUGINS COUNTER:   !total_plugins!
echo =================================================================
echo.
pause
goto MAIN_MENU

:: =================================================================
:: [6] DIAGNOSTIC: CUSTOM MOD ARCHIVE ^& CORES SCANNER
:: =================================================================
:ANALYZE_MOD_SIZE
cls
echo ==========================================================
echo               🩺 PRO-MOD DIAGNOSTIC HUB
echo ==========================================================
echo.
echo    [1] 📊 OVERVIEW: Core File Counts ^& Heavy BSA Scan
echo.
echo    [2] 🛡️  AUDITOR:  Creation Club ^& Master Checks
echo.
echo    [3] 💾 SYSTEM:   Dirty Plugins ^& Save File Health
echo.
echo    [4] 📅 SCAN:     Recent Plugin Modifications (Last 30 Days)
echo.
echo    [5] 🗄️  TOOL:     Archive Old Save Games (Keep 50)
echo.
echo    [6] 🔍 AUDITOR: PLUGIN INTEGRITY ^& CORRUPTION SCAN
echo.
echo    [X] ❌ EXIT:     Return to Main Menu
echo ==========================================================
set /p "CHOICE=Select diagnostic routine: "

if "%CHOICE%"=="1" goto SCAN_1
if "%CHOICE%"=="2" goto SCAN_2
if "%CHOICE%"=="3" goto SCAN_3
if "%CHOICE%"=="4" goto SCAN_4
if "%CHOICE%"=="5" goto SCAN_5
if "%CHOICE%"=="6" goto SCAN_6
if /i "%CHOICE%"=="X" goto MAIN_MENU
goto ANALYZE_MOD_SIZE

:SCAN_1
cls
powershell -NoProfile -Command ^
    "$allFiles = Get-ChildItem '%SKYRIM_DIR%\Data' -File -ErrorAction SilentlyContinue;" ^
    "$esms = ($allFiles | Where-Object { $_.Extension -eq '.esm' }).Count;" ^
    "$esls = ($allFiles | Where-Object { $_.Extension -eq '.esl' }).Count;" ^
    "$esps = ($allFiles | Where-Object { $_.Extension -eq '.esp' }).Count;" ^
    "$topBSAs = $allFiles | Where-Object { $_.Extension -eq '.bsa' -and $_.Name -notlike 'Skyrim*' -and $_.Name -notlike 'Dawnguard*' -and $_.Name -notlike 'HearthFires*' -and $_.Name -notlike 'Dragonborn*' } | Sort-Object Length -Descending | Select-Object -First 5;" ^
    "Write-Host '==========================================================';" ^
    "Write-Host '            CUSTOM MOD ARCHIVE & CORES SCANNER';" ^
    "Write-Host '==========================================================';" ^
    "Write-Host ' Target Path: %SKYRIM_DIR%\Data';" ^
    "Write-Host '----------------------------------------------------------';" ^
    "Write-Host '==================== PHYSICAL FILE COUNTS ====================';" ^
    "Write-Host ' [+] Raw Master Files (.esm):      ' $esms;" ^
    "Write-Host ' [+] Raw Light Files (.esl):       ' $esls;" ^
    "Write-Host ' [+] Raw Standard Files (.esp):    ' $esps;" ^
    "Write-Host '----------------------------------------------------------';" ^
    "Write-Host '==================== HEAVIEST CUSTOM MODS ====================';" ^
    "if ($topBSAs) { foreach ($i in 0..($topBSAs.Count-1)) { Write-Host \"    [$($i+1)] $($topBSAs[$i].Name) ($([math]::round($topBSAs[$i].Length/1MB, 2)) MB)\"; } } else { Write-Host ' No custom BSA files found.' }" ^
    "Write-Host '=========================================================='"
echo.
set /p "CHECK_DISK=If you'd like to view disk space/engine limits press Y (otherwise press Enter): "
if /i "%CHECK_DISK%"=="Y" goto DISK_MATH
goto :ANALYZE_MOD_SIZE

:DISK_MATH
:: Get the drive letter from the SKYRIM_DIR path (which is G:\...)
:: This grabs the first letter of the string (G)
set "DRIVE_LETTER=%SKYRIM_DIR:~0,1%"

powershell -NoProfile -Command ^
    "$modSize = [math]::round((Get-ChildItem '%VORTEX_DIR%' -Recurse -File -ErrorAction SilentlyContinue | Measure-Object -Property Length -Sum).Sum / 1GB, 2);" ^
    "$drive = Get-Volume -DriveLetter '%DRIVE_LETTER%' -ErrorAction SilentlyContinue;" ^
    "if ($drive) {" ^
    "  $driveFree = [math]::round($drive.SizeRemaining / 1GB, 2);" ^
    "  $driveTotal = [math]::round($drive.Size / 1GB, 2);" ^
    "  $freePercent = if ($driveTotal -gt 0) { [math]::round(($driveFree / $driveTotal) * 100, 1) } else { 0 };" ^
    "  Write-Host '=================================================================';" ^
    "  Write-Host '            DIAGNOSTIC: ENGINE LIMITS & STORAGE HEALTH';" ^
    "  Write-Host '=================================================================';" ^
    "  Write-Host \"  Vortex Mod Directory Size : $modSize GB\";" ^
    "  Write-Host \"  Drive Free Space on %DRIVE_LETTER%: : $driveFree GB / $driveTotal GB ($freePercent%% Free)\";" ^
    "} else {" ^
    "  Write-Host ' [!] Could not retrieve volume info for drive %DRIVE_LETTER%:' -ForegroundColor Red;" ^
    "}" ^
    "Write-Host '======================= ENGINE LIMITS ========================';" ^
    "Write-Host '  Heavy Plugins (ESP/ESM)   : 319 / 254';" ^
    "Write-Host '  Light Plugins (ESL)       : 14 / 4096';" ^
    "Write-Host '==============================================================';" ^
    "if (319 -gt 254) { Write-Host ' [⚠️ WARNING] Approaching ESP/ESM Hard Limit.' -ForegroundColor Yellow; }"
pause
goto :ANALYZE_MOD_SIZE

:SCAN_2
cls
echo ==========================================================
echo              🛡️ AUDITOR: CREATION CLUB CHECK
echo ==========================================================
powershell -NoProfile -Command ^
    "$ccFiles = Get-ChildItem '%SKYRIM_DIR:"=%' -Filter 'cc*.esp' -Recurse;" ^
    "if ($ccFiles.Count -gt 0) { Write-Host ' [+] Found' $ccFiles.Count 'Creation Club plugin files.' -ForegroundColor Cyan; " ^
    "$ccFiles | Select-Object -First 10 | ForEach-Object { Write-Host '   -' $_.Name }; } " ^
    "else { Write-Host ' [!] No specific Creation Club plugins detected.'; }"
echo ----------------------------------------------------------
pause
goto :ANALYZE_MOD_SIZE

:SCAN_3
cls
echo ==========================================================
echo          💾 SYSTEM: DIRTY PLUGINS ^& SAVE FILE HEALTH
echo ==========================================================
:: Safety Gate: Check if variables are set
if "%SAVE_DIR%"=="" (
    echo [!] ERROR: SAVE_DIR is not defined in your config.
    echo Please check your setup routine.
    pause
    goto :ANALYZE_MOD_SIZE
)

:: If safe, run the command
powershell -NoProfile -Command " & { $d = Get-ChildItem '%DATA_DIR%' -Filter *.esp | Where-Object { $_.LastWriteTime -gt (Get-Date).AddDays(-1) }; $s = if(Test-Path '%SAVE_DIR%') { Get-ChildItem '%SAVE_DIR%' -Filter *.ess } else { @() }; Write-Host ' [+] Modified Plugins (Last 24h):' $d.Count; Write-Host ' [+] Total Save Files in Profile:' $s.Count; if($s.Count -gt 1000) { Write-Host ' [!] High save count detected' -ForegroundColor Yellow } }"
echo ----------------------------------------------------------
pause
goto :ANALYZE_MOD_SIZE

:SCAN_4
cls
echo ==========================================================
echo          📅 SCAN: RECENT PLUGIN MODIFICATIONS
echo ==========================================================
powershell -NoProfile -Command "& { $found = Get-ChildItem '%DATA_DIR%' -Filter *.esp | Where-Object { $_.LastWriteTime -gt (Get-Date).AddDays(-30) }; if ($found.Count -eq 0) { Write-Host ' No plugins modified in the last 30 days. Load order is stable.' -ForegroundColor Green } else { $found | ForEach-Object { Write-Host ' [!] Found: ' $_.Name ' (Modified:' $_.LastWriteTime ')' -ForegroundColor Yellow } } }"
echo ----------------------------------------------------------
pause
goto :ANALYZE_MOD_SIZE

:SCAN_5
cls
echo ==========================================================
echo           🗄️ TOOL: ARCHIVE OLD SAVE GAMES (%Yeardate%)
echo ==========================================================
if not exist "%SAVE_DIR%\Archive_%Yeardate%" mkdir "%SAVE_DIR%\Archive_%Yeardate%"

powershell -NoProfile -Command "& { $saves = Get-ChildItem '%SAVE_DIR%' -Filter *.ess; Write-Host 'Total saves found:' $saves.Count; if ($saves.Count -gt 50) { Write-Host 'Archiving oldest saves...' -ForegroundColor Cyan; $sorted = $saves | Sort-Object LastWriteTime; $toArchive = $sorted[0..($sorted.Count-51)]; foreach ($s in $toArchive) { Move-Item -Path $s.FullName -Destination '%SAVE_DIR%\Archive_%Yeardate%' }; Write-Host 'Successfully moved' $toArchive.Count 'saves.' -ForegroundColor Green } else { Write-Host 'Save count is' $saves.Count '. Nothing to archive.' -ForegroundColor Yellow } }"
echo ----------------------------------------------------------
pause
goto :ANALYZE_MOD_SIZE

:SCAN_6
cls
echo ==========================================================
echo           🔍 AUDITOR: PLUGIN INTEGRITY ^& CORRUPTION SCAN
echo ==========================================================
echo  STATUS: Physical file health.
echo  ACTION: If a plugin is flagged RED, redownload/reinstall 
echo          the mod in your Mod Manager.
echo ==========================================================
echo ==========================================================
:: We list files to ensure the directory is readable and healthy
powershell -NoProfile -Command ^
    "$plugins = Get-ChildItem '%DATA_DIR%' -Filter *.esp;" ^
    "foreach ($p in $plugins) {" ^
    "    if ($p.Length -lt 100) {" ^
    "        Write-Host ' [!] SUSPICIOUSLY SMALL PLUGIN:' $p.Name -ForegroundColor Red;" ^
    "    } else {" ^
    "        Write-Host ' [OK] Plugin verified:' $p.Name -ForegroundColor Green;" ^
    "    }" ^
    "}"
echo ----------------------------------------------------------
echo  Scan complete.
echo  [!] If a plugin is marked RED, it is missing or corrupted.
echo      ACTION: Redownload/Reinstall the mod in Vortex.
echo  [?] If you still have issues, check Vortex for 
echo      "Missing Master" dependency errors.
echo ----------------------------------------------------------
pause
goto :ANALYZE_MOD_SIZE

:RUN_SETUP_ROUTINE
cls
echo =================================================================
echo    ⚙️  SKYRIM CONTROL CENTER: INITIAL SETUP WIZARD
echo =================================================================
echo.
echo    [1] ⌨️  Standard CMD Mode: (Copy/Paste paths)
echo.
echo    [2] 🖥️  Interactive Mode:  (File Explorer Selection)
echo.
echo =================================================================
set "mode_choice="
set /p "mode_choice=Select configuration entry mode (1-2): "

if "%mode_choice%"=="1" goto ROUTINE_CMD_MODE
if "%mode_choice%"=="2" goto ROUTINE_POWERSHELL_MODE
goto RUN_SETUP_ROUTINE

:: -----------------------------------------------------------------
:: CMD PATH COLLECTION
:: -----------------------------------------------------------------
:ROUTINE_CMD_MODE
set "MODE=CMD"
echo =================================================================
echo Example: C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition
set /p "SKYRIM_DIR=1. Paste your main Skyrim SE Root Installation folder: "
goto MOD_MANAGER_HUB

:: -----------------------------------------------------------------
:: POWERSHELL PATH COLLECTION
:: -----------------------------------------------------------------
:ROUTINE_POWERSHELL_MODE
set "MODE=PS"
echo ➡️ Selecting Skyrim Root...
:: Add this echo so they see the format you want if they end up needing to type it
echo Example: G:\Steam\steamapps\common\Skyrim Special Edition
set "ps_cmd=Add-Type -AssemblyName System.Windows.Forms; $f = New-Object System.Windows.Forms.FolderBrowserDialog; if($f.ShowDialog() -eq 'OK') { Write-Output $f.SelectedPath }"
for /f "usebackq delims=" %%I in (`powershell -NoProfile -STA -ExecutionPolicy Bypass -Command "%ps_cmd%" 2^>nul`) do set "SKYRIM_DIR=%%I"

:: Add a quick check to make sure they actually picked something
if "%SKYRIM_DIR%"=="" (
    echo [!] Path selection cancelled.
    goto ROUTINE_POWERSHELL_MODE
)
goto MOD_MANAGER_HUB

:MOD_MANAGER_HUB
cls
echo =================================================================
echo              📦[MOD ORGANIZER HUB]
echo =================================================================
echo  [1] Vortex          [D1] Download: https://www.nexusmods.com/site/mods/1
echo  [2] Mod Organizer 2 [D2] Download: https://www.nexusmods.com/skyrimspecialedition/mods/6194
echo  [3] Wabbajack       [D3] Download: https://www.wabbajack.org/
echo  [S] Skip All (No Manager)
echo =================================================================
set /p "MO_CHOICE=Select (1-3) or (D1-D3) to download: "

:: 1. Handle Downloads
if /i "%MO_CHOICE%"=="D1" start "" "https://www.nexusmods.com/site/mods/1" & goto MOD_MANAGER_HUB
if /i "%MO_CHOICE%"=="D2" start "" "https://www.nexusmods.com/skyrimspecialedition/mods/6194" & goto MOD_MANAGER_HUB
if /i "%MO_CHOICE%"=="D3" start "" "https://www.wabbajack.org/" & goto MOD_MANAGER_HUB

:: 2. Handle Skip
if /i "%MO_CHOICE%"=="S" (
    set "VORTEX_DIR=NONE"
    set "VORTEX_EXE=NONE"
    goto DOCS_PROFILE_SELECTOR
)

:: 3. Define Labels based on choice
if "%MO_CHOICE%"=="1" set "LABEL=Staging Folder"
if "%MO_CHOICE%"=="2" set "LABEL=Mods/Instance Folder"
if "%MO_CHOICE%"=="3" set "LABEL=Install/Base Folder"

:: Validate Choice
if "%LABEL%"=="" goto MOD_MANAGER_HUB

:: 4. Path Collection
if "%MODE%"=="CMD" (
    echo --------------------------------------------------------------
    set /p "VORTEX_DIR=Paste your %LABEL% path: "
    echo --------------------------------------------------------------
    set /p "VORTEX_EXE=Paste full path to main .exe (or just paste the folder): "
) else (
    echo ➡️ Selecting %LABEL%...
    :: Path Picker
    for /f "usebackq delims=" %%I in (`powershell -NoProfile -STA -ExecutionPolicy Bypass -Command "Add-Type -AssemblyName System.Windows.Forms; $f=New-Object System.Windows.Forms.FolderBrowserDialog; $f.Description = 'Select %LABEL%'; if($f.ShowDialog() -eq 'OK'){Write-Output $f.SelectedPath}"`) do set "VORTEX_DIR=%%I"
    :: Exe Picker
    for /f "usebackq delims=" %%I in (`powershell -NoProfile -STA -ExecutionPolicy Bypass -Command "Add-Type -AssemblyName System.Windows.Forms; $f=New-Object System.Windows.Forms.OpenFileDialog; $f.Title = 'Locate main .exe'; if($f.ShowDialog() -eq 'OK'){Write-Output $f.FileName}"`) do set "VORTEX_EXE=%%I"
)

:: 5. Auto-Append Executable if user only pasted the folder
if not "!VORTEX_EXE!"=="" (
    set "EXE_CHECK=!VORTEX_EXE:~-4!"
    if /i not "!EXE_CHECK!"==".exe" (
        :: Remove trailing slash if the user accidentally included one
        if "!VORTEX_EXE:~-1!"=="\" set "VORTEX_EXE=!VORTEX_EXE:~0,-1!"
        
        :: Add the correct .exe based on their manager choice
        if "%MO_CHOICE%"=="1" set "VORTEX_EXE=!VORTEX_EXE!\vortex.exe"
        if "%MO_CHOICE%"=="2" set "VORTEX_EXE=!VORTEX_EXE!\ModOrganizer.exe"
		if "%MO_CHOICE%"=="3" set "VORTEX_EXE=!VORTEX_EXE!\Wabbajack.exe"
    )
)

goto DOCS_PROFILE_SELECTOR

:: -----------------------------------------------------------------
:: PROFILE SELECTION: VISUAL CHECK VIA WINDOWS EXPLORER
:: -----------------------------------------------------------------
:DOCS_PROFILE_SELECTOR
cls
echo =================================================================
echo             CRITICAL: LOCATING YOUR SKYRIM USER PROFILE
echo =================================================================
echo   WHY ARE YOU SEEING THIS SCREEN?
echo   Skyrim relies heavily on your Windows 'Documents' folder to load
echo   your game saves, initialization files (Skyrim.ini), and your 
echo   SKSE plugin crash logs. 
echo.
echo   Modern Windows (10 or 11) often silently relocates this folder into OneDrive.
echo   If this toolkit points to the wrong location, your Explorer Hub
echo   won't be able to find your crash logs or ini files.
echo.
echo   Let's check where your 'My Games' folder actually lives:
echo -----------------------------------------------------------------
echo   [1] 📂 Open Local Documents    (%USERPROFILE%\Documents)
echo   [2] ☁️ Open OneDrive Documents (%USERPROFILE%\OneDrive\Documents)
echo -----------------------------------------------------------------
echo   💡 Know your path already? Skip the Search and lock it in directly:
echo   [U] Fast-Lock to Local User Profile
echo   [O] Fast-Lock to OneDrive Profile
echo   [S] Skip Diagnostics (Dashboard Only)
echo -----------------------------------------------------------------
echo   👉 Press 1 or 2 to open that directory in Windows Explorer.
echo   👉 Or press U or O to immediately save and bypass scouting.
echo =================================================================
echo.
set "check_choice="
set /p "check_choice=Select menu option or command: "

:: Instant Fast-Bypass logic mapping
if /i "%check_choice%"=="U" set "DOCS_BASE=%USERPROFILE%\Documents" & goto WRITE_INI_DATABASE
if /i "%check_choice%"=="O" set "DOCS_BASE=%USERPROFILE%\OneDrive\Documents" & goto WRITE_INI_DATABASE
if /i "%check_choice%"=="S" set "DOCS_BASE=Not Available" & goto WRITE_INI_DATABASE

:: Standard Visual Scout mapping
if "%check_choice%"=="1" (
    echo Opening Local Documents window...
    explorer "%USERPROFILE%\Documents"
    goto CONFIRM_DOCS_PATH
)
if "%check_choice%"=="2" (
    echo Opening OneDrive Documents window...
    explorer "%USERPROFILE%\OneDrive\Documents"
    goto CONFIRM_DOCS_PATH
)
goto DOCS_PROFILE_SELECTOR

:CONFIRM_DOCS_PATH
echo.
echo =================================================================
echo                      LOCK IN YOUR SELECTION
echo =================================================================
echo   Based on the Windows Explorer window you just looked at, 
echo   where did you successfully find your 'My Games' folder?
echo.
echo   [U] Locked to USER PROFILE (Local)
echo   [O] Locked to ONEDRIVE     (Cloud)
echo =================================================================
echo.
set "confirm_choice="
set /p "confirm_choice=Type your choice (U or O): "

if /i "%confirm_choice%"=="U" set "DOCS_BASE=%USERPROFILE%\Documents" & goto WRITE_INI_DATABASE
if /i "%confirm_choice%"=="O" set "DOCS_BASE=%USERPROFILE%\OneDrive\Documents" & goto WRITE_INI_DATABASE
goto CONFIRM_DOCS_PATH

:: =================================================================
:: SANITIZE VARIABLES & COMPILE TO .INI CONFIGURATION MATRIX
:: =================================================================
:WRITE_INI_DATABASE
cls
:: Strip quotes
set "SKYRIM_DIR=%SKYRIM_DIR:"=%"
set "VORTEX_DIR=%VORTEX_DIR:"=%"
set "VORTEX_EXE=%VORTEX_EXE:"=%"
set "DOCS_BASE=%DOCS_BASE:"=%"

:: Auto-calculate pathways
set "SKSE_PATH=%SKYRIM_DIR%\skse64_loader.exe"
:: Build the standard path from your DOCS_BASE variable
set "SAVE_DIR=%DOCS_BASE%\My Games\Skyrim Special Edition\Saves"

:: Compile everything
(
    echo SKYRIM_DIR=%SKYRIM_DIR%
    echo SKSE_PATH=%SKSE_PATH%
    echo VORTEX_DIR=%VORTEX_DIR%
    echo VORTEX_EXE=%VORTEX_EXE%
    echo DOCS_BASE=%DOCS_BASE%
    echo SAVE_DIR=%SAVE_DIR%
) > "%CONFIG_FILE%"

echo =================================================================
echo                INI ENVIRONMENT DATABASE COMPILED
echo =================================================================
echo  Data successfully saved including SAVE_DIR.
timeout /t 2 > nul
goto INIT_CHECK